"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { Input as FormInput, Textarea as FormTextarea, Button } from "@/components/ui";
import { prepareImageForUpload, prepareImageErrorMessage } from "@/lib/image-client";

export type GiftFormInitialData = {
  giftName: string;
  title: string;
  description: string;
  organizerName: string;
  targetAmount: string;
  raisedCents: number;
  imageUrl: string | null;
  imageZoom: number;
  imageOffsetX: number;
  imageOffsetY: number;
  aiImagesGenerated: number;
  imageGallery: string | null;
};

const EMPTY_INITIAL: GiftFormInitialData = {
  giftName: "",
  title: "",
  description: "",
  organizerName: "",
  targetAmount: "",
  raisedCents: 0,
  imageUrl: null,
  imageZoom: 1,
  imageOffsetX: 0,
  imageOffsetY: 0,
  aiImagesGenerated: 0,
  imageGallery: null,
};

const MAX_PAINTINGS = 5;

type GridImage = { url: string; source: "painting" | "upload" };

function FieldHint({ text }: { text: string }) {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button
        type="button"
        aria-label="Show hint"
        aria-expanded={open}
        onClick={() => setOpen((v) => !v)}
        className="ml-1 inline-flex h-5 w-5 items-center justify-center rounded-full border border-zinc-200 text-[11px] font-medium text-zinc-400 transition-colors hover:border-zinc-300 hover:text-zinc-600 dark:border-zinc-700 dark:text-zinc-500 dark:hover:border-zinc-600 dark:hover:text-zinc-300"
      >
        ?
      </button>
      {open && (
        <p className="mt-1 w-full rounded-lg bg-zinc-50 px-3 py-2 text-xs text-zinc-500 dark:bg-zinc-900 dark:text-zinc-400">
          {text}
        </p>
      )}
    </>
  );
}

export function GiftForm({
  mode,
  giftId,
  initialData,
}: {
  mode: "create" | "edit";
  giftId?: string;
  initialData?: GiftFormInitialData;
}) {
  const router = useRouter();
  const init = initialData || EMPTY_INITIAL;

  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  const [giftName, setGiftName] = useState(init.giftName);
  const [title, setTitle] = useState(init.title);
  const [description, setDescription] = useState(init.description);
  const [organizerName, setOrganizerName] = useState(init.organizerName);
  const [targetAmount, setTargetAmount] = useState(init.targetAmount);

  // Image grid state
  const [images, setImages] = useState<GridImage[]>(() => {
    if (init.imageGallery) {
      try {
        return JSON.parse(init.imageGallery) as GridImage[];
      } catch { /* fall through */ }
    }
    if (init.imageUrl) return [{ url: init.imageUrl, source: "upload" }];
    return [];
  });
  const [selectedUrl, setSelectedUrl] = useState<string | null>(init.imageUrl);
  const [generating, setGenerating] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [paintingCount, setPaintingCount] = useState(init.aiImagesGenerated);
  const [paintingMessage, setPaintingMessage] = useState("");
  const [giftNameAtLastGen, setGiftNameAtLastGen] = useState("");
  const hasAutoGenerated = useRef(mode === "edit");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const formRef = useRef<HTMLFormElement>(null);

  function saveGallery(updatedImages: GridImage[], selected: string | null) {
    if (mode !== "edit" || !giftId) return;
    fetch(`/api/gifts/${giftId}/gallery`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        og_image: selected || undefined,
        image_gallery: updatedImages.length > 0 ? JSON.stringify(updatedImages) : undefined,
      }),
    }).catch(() => {});
  }

  function removeImage(url: string) {
    const updated = images.filter((img) => img.url !== url);
    const newSelected = selectedUrl === url ? null : selectedUrl;
    setImages(updated);
    setSelectedUrl(newSelected);
    saveGallery(updated, newSelected);
  }

  const generatePainting = useCallback(async (name: string) => {
    if (generating) return;
    // Server requires gift_id to enforce the per-gift painting cap, so we
    // can't generate until the gift exists (create mode saves first, then the
    // user lands on the edit view where this button becomes available).
    if (mode !== "edit" || !giftId) return;
    if (paintingCount >= MAX_PAINTINGS) {
      setPaintingMessage("You've used all your Giftaro paintings");
      return;
    }

    setGenerating(true);
    setPaintingMessage("");
    setError("");

    try {
      const res = await fetch("/api/generate-painting", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          gift_name: name,
          gift_id: giftId,
        }),
      });

      const data = await res.json();
      if (res.ok) {
        const newImage: GridImage = { url: data.url, source: "painting" };
        setImages((prev) => [newImage, ...prev]);
        setSelectedUrl(data.url);
        setGiftNameAtLastGen(name);
        const newCount = data.count ?? paintingCount + 1;
        setPaintingCount(newCount);
        if (newCount === MAX_PAINTINGS - 1) {
          setPaintingMessage("You only have one Giftaro painting left…make it count");
        } else if (newCount >= MAX_PAINTINGS) {
          setPaintingMessage("You've used all your Giftaro paintings");
        }
      } else {
        setError(data.error || "Failed to generate painting");
      }
    } catch {
      setError("Failed to generate painting. Please try again.");
    } finally {
      setGenerating(false);
    }
  }, [generating, paintingCount, mode, giftId]);

  // Auto-trigger painting generation — edit mode only. In create mode there
  // is no gift_id yet, and the server requires one to enforce the per-gift
  // painting cap.
  const handleFieldFocus = useCallback((fieldName: string) => {
    if (mode !== "edit") return;
    if (fieldName === "giftName" || fieldName === "title") return;
    if (hasAutoGenerated.current || generating) return;
    const hasPaintings = images.some((img) => img.source === "painting");
    if (hasPaintings) return;
    const nameVal = giftName.trim();
    const titleVal = title.trim();
    if (nameVal.length >= 1 && titleVal.length >= 1) {
      hasAutoGenerated.current = true;
      generatePainting(nameVal);
    }
  }, [mode, giftName, title, generating, images, generatePainting]);

  // Clear "one left" message after a few seconds (keep "used all" permanent)
  useEffect(() => {
    if (!paintingMessage || paintingCount >= MAX_PAINTINGS) return;
    const t = setTimeout(() => setPaintingMessage(""), 6000);
    return () => clearTimeout(t);
  }, [paintingMessage, paintingCount]);

  // Painting button conditions — edit mode only (server-side cap requires
  // an existing gift_id, so we can't offer the action in create mode).
  const canGeneratePainting =
    mode === "edit" &&
    giftName.trim().length > 0 &&
    paintingCount < MAX_PAINTINGS &&
    !generating;
  const showNewPaintingBtn =
    canGeneratePainting &&
    giftNameAtLastGen !== "" &&
    giftName.trim() !== giftNameAtLastGen;
  const showGeneratePaintingBtn =
    canGeneratePainting &&
    giftNameAtLastGen === "";

  const handleFileUpload = useCallback(async (file: File) => {
    if (!file.type.startsWith("image/")) return;

    setUploading(true);
    setError("");

    const prepared = await prepareImageForUpload(file);
    if ("error" in prepared) {
      setError(prepareImageErrorMessage(prepared.error));
      setUploading(false);
      return;
    }

    try {
      const formData = new FormData();
      formData.append("file", prepared.file);
      const res = await fetch("/api/upload", { method: "POST", body: formData });
      if (res.ok) {
        const { url } = await res.json();
        const newImage: GridImage = { url, source: "upload" };
        setImages((prev) => {
          const updated = [...prev, newImage];
          setSelectedUrl(url);
          saveGallery(updated, url);
          return updated;
        });
      } else {
        const data = await res.json();
        setError(data.error || "Upload failed");
      }
    } catch {
      setError("Upload failed. Please try again.");
    } finally {
      setUploading(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode, giftId]);

  // Paste-from-clipboard: lets users drop in a screenshot they just copied
  useEffect(() => {
    function onPaste(e: ClipboardEvent) {
      if (!e.clipboardData) return;
      const target = e.target as HTMLElement | null;
      // Don't hijack paste in text fields
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) {
        const type = (target as HTMLInputElement).type;
        if (type !== "file") return;
      }
      const items = Array.from(e.clipboardData.items);
      const imageItem = items.find((it) => it.type.startsWith("image/"));
      if (!imageItem) return;
      const file = imageItem.getAsFile();
      if (!file) return;
      e.preventDefault();
      handleFileUpload(file);
    }
    window.addEventListener("paste", onPaste);
    return () => window.removeEventListener("paste", onPaste);
  }, [handleFileUpload]);

  function handleDrop(e: React.DragEvent) {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) handleFileUpload(file);
  }

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setSubmitting(true);
    setError("");

    if (!organizerName.trim()) {
      setError("Organizer name is required");
      setSubmitting(false);
      return;
    }

    const dollarAmount = parseFloat(targetAmount);
    if (!dollarAmount || dollarAmount < 10) {
      setError("Goal amount must be at least $10");
      setSubmitting(false);
      return;
    }

    const cents = Math.round(dollarAmount * 100);
    if (mode === "edit" && init.raisedCents > 0 && cents < init.raisedCents) {
      setError(`Goal can't be less than $${(init.raisedCents / 100).toFixed(0)} already raised`);
      setSubmitting(false);
      return;
    }

    const payload = {
      title,
      description: description || undefined,
      organizer_name: organizerName.trim(),
      target_amount_cents: cents,
      og_image: selectedUrl || undefined,
      og_title: giftName || undefined,
      image_zoom: selectedUrl === init.imageUrl && init.imageUrl ? init.imageZoom : 1,
      image_offset_x: selectedUrl === init.imageUrl && init.imageUrl ? init.imageOffsetX : 0,
      image_offset_y: selectedUrl === init.imageUrl && init.imageUrl ? init.imageOffsetY : 0,
      image_gallery: images.length > 0 ? JSON.stringify(images) : undefined,
    };

    try {
      const url = mode === "create" ? "/api/gifts" : `/api/gifts/${giftId}`;
      const method = mode === "create" ? "POST" : "PATCH";
      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const data = await res.json();
      if (res.ok) {
        const id = mode === "create" ? data.id : giftId;
        const query = mode === "create" ? "?created=true" : "";
        router.push(`/dashboard/gifts/${id}${query}`);
      } else {
        setError(data.error || `Failed to ${mode === "create" ? "create" : "save"} gift page`);
        setSubmitting(false);
      }
    } catch {
      setError("Connection error. Please try again.");
      setSubmitting(false);
    }
  }

  const CELL = "h-[120px] w-[120px]";

  return (
    <form
      ref={formRef}
      onSubmit={handleSubmit}
      onDragEnter={(e) => {
        if (e.dataTransfer.types?.includes("Files")) {
          e.preventDefault();
          setIsDragging(true);
        }
      }}
      onDragOver={(e) => {
        if (e.dataTransfer.types?.includes("Files")) {
          e.preventDefault();
        }
      }}
      onDragLeave={(e) => {
        if (e.currentTarget === e.target) setIsDragging(false);
      }}
      onDrop={handleDrop}
      className="relative flex flex-col gap-4"
    >
      {isDragging && (
        <div className="pointer-events-none absolute inset-0 z-10 flex items-center justify-center rounded-xl border-2 border-dashed border-brand bg-brand/5 text-sm font-medium text-brand">
          Drop image to upload
        </div>
      )}
      {/* What's the gift? */}
      <div>
        <div className="mb-1 flex items-center justify-between">
          <div className="flex items-center">
            <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
              What&apos;s the gift?
            </label>
            <FieldHint text="Let people know what they're contributing to." />
          </div>
          {(showNewPaintingBtn || showGeneratePaintingBtn) && (
            <button
              type="button"
              onClick={() => generatePainting(giftName.trim())}
              className="flex items-center gap-1 rounded-full border border-brand/30 bg-brand/5 px-2.5 py-0.5 text-[11px] font-medium text-brand transition-colors hover:bg-brand/10 active:scale-95"
            >
              <img src="/paintbrush.png" alt="" className="h-3.5 w-3.5" />
              {showNewPaintingBtn ? "New painting" : "Generate painting"}
              <span className="text-brand/50">{paintingCount}/{MAX_PAINTINGS}</span>
            </button>
          )}
        </div>
        <FormInput
          required
          value={giftName}
          onChange={(e) => setGiftName(e.target.value)}
          onFocus={() => handleFieldFocus("giftName")}
          placeholder="Trek mountain bike, PS5, AirPods..."
        />
      </div>

      {/* What's the gift for? */}
      <div>
        <div className="mb-1 flex items-center">
          <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
            What&apos;s it for?
          </label>
          <FieldHint text="Let people know the occasion for the gift." />
        </div>
        <FormInput
          required
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          onFocus={() => handleFieldFocus("title")}
          placeholder="Emma's birthday"
        />
      </div>

      {/* Goal amount */}
      <div>
        <div className="mb-1 flex items-center">
          <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
            Gift amount ($)
          </label>
          <FieldHint text="How much do you want to raise before buying this gift?" />
        </div>
        <FormInput
          type="number"
          required
          min="1"
          step="0.01"
          value={targetAmount}
          onChange={(e) => setTargetAmount(e.target.value)}
          onFocus={() => handleFieldFocus("targetAmount")}
          placeholder="150"
        />
        {mode === "edit" && init.raisedCents > 0 && (
          <p className="mt-1 text-xs text-zinc-400">
            {`$${(init.raisedCents / 100).toFixed(0)} already raised — goal can't be lower than this`}
          </p>
        )}
      </div>

      {/* Organizer name */}
      <div>
        <label className="mb-1 block text-sm font-medium text-zinc-700 dark:text-zinc-300">
          Organized by
        </label>
        <FormInput
          required
          value={organizerName}
          onChange={(e) => setOrganizerName(e.target.value)}
          onFocus={() => handleFieldFocus("organizerName")}
          placeholder="Your name"
        />
      </div>

      {/* Image grid */}
      <div>
        <div className="mb-2 flex items-center">
          <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
            Gift image (optional)
          </label>
          <FieldHint text="It's nice for people to see a picture of the gift. A simple screenshot works — paste or drop one in." />
        </div>
        <div className="grid grid-cols-3 gap-3">
          {/* Generating spinner cell */}
          {generating && (
            <div className={`${CELL} flex items-center justify-center rounded-xl border-2 border-zinc-200 bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-800`}>
              <div className="flex flex-col items-center gap-1">
                <img
                  src="/paintbrush.png"
                  alt=""
                  className="h-10 w-10 animate-[painting_1.2s_ease-in-out_infinite]"
                />
                <span className="text-[9px] font-medium text-zinc-400">Giftaro is painting</span>
              </div>
            </div>
          )}

          {/* Image cells */}
          {images.map((img) => (
            <button
              key={img.url}
              type="button"
              onClick={() => setSelectedUrl(selectedUrl === img.url ? null : img.url)}
              className={`relative ${CELL} flex-shrink-0 overflow-hidden rounded-xl border-2 transition-all ${
                selectedUrl === img.url
                  ? "border-green-500 ring-2 ring-green-500/20"
                  : "border-zinc-200 dark:border-zinc-700"
              } bg-zinc-100 dark:bg-zinc-800`}
            >
              <img
                src={img.url}
                alt={img.source === "painting" ? "AI painting" : "Uploaded photo"}
                className="h-full w-full object-contain p-1"
              />
              {/* Selection checkmark */}
              {selectedUrl === img.url && (
                <div className="absolute right-1.5 top-1.5 flex h-5 w-5 items-center justify-center rounded-full bg-white shadow-sm">
                  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#22c55e" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                </div>
              )}
              {/* X remove button */}
              <div
                role="button"
                onClick={(e) => {
                  e.stopPropagation();
                  removeImage(img.url);
                }}
                className="absolute left-1.5 top-1.5 flex h-5 w-5 items-center justify-center rounded-full bg-black/50 text-white opacity-0 transition-opacity hover:bg-black/70 group-hover:opacity-100 [button:hover>&]:opacity-100"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                  <line x1="18" x2="6" y1="6" y2="18" />
                  <line x1="6" x2="18" y1="6" y2="18" />
                </svg>
              </div>
            </button>
          ))}

          {/* Upload button cell */}
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            disabled={uploading}
            className={`${CELL} flex flex-col items-center justify-center gap-1 rounded-xl border-2 border-dashed border-zinc-300 text-zinc-400 transition-colors hover:border-zinc-400 hover:text-zinc-600 dark:border-zinc-700 dark:text-zinc-500 dark:hover:border-zinc-600 dark:hover:text-zinc-300`}
          >
            {uploading ? (
              <div className="h-5 w-5 animate-spin rounded-full border-2 border-zinc-300 border-t-zinc-600" />
            ) : (
              <>
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="17 8 12 3 7 8" />
                  <line x1="12" x2="12" y1="3" y2="15" />
                </svg>
                <span className="text-[11px] font-medium">Upload photo</span>
              </>
            )}
          </button>
        </div>

        <p className="mt-2 text-xs text-zinc-400">
          Tip: paste a screenshot or drag an image anywhere on this form.
        </p>

        {/* Painting limit message */}
        {paintingMessage && (
          <p className="mt-2 text-xs text-zinc-400">{paintingMessage}</p>
        )}

        <input
          ref={fileInputRef}
          type="file"
          accept="image/jpeg,image/png,image/webp,image/gif,image/heic,image/heif,.heic,.heif"
          className="hidden"
          onChange={(e) => {
            const file = e.target.files?.[0];
            if (file) handleFileUpload(file);
            e.target.value = "";
          }}
        />
      </div>

      {/* Description */}
      <div>
        <label className="mb-1 block text-sm font-medium text-zinc-700 dark:text-zinc-300">
          Add a note (optional)
        </label>
        <FormTextarea
          rows={3}
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          onFocus={() => handleFieldFocus("description")}
          placeholder="We're saving up for a new bike!"
        />
      </div>

      {error && (
        <p className="text-sm text-red-500">{error}</p>
      )}

      <Button type="submit" disabled={submitting} className="mt-2">
        {submitting
          ? mode === "create" ? "Creating..." : "Saving..."
          : mode === "create" ? "Start your gift" : "Save changes"
        }
      </Button>
    </form>
  );
}
